### ISSUE TITLE
Manual testing of RC 2022.10.1

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1125]
**Initial set-up**

*Check that the IntelliJ Idea UTBot plugin can be successfully installed*

- [x] Choose appropriate workflow from the list (by default, filter by main branch and take the latest one) https://github.com/UnitTestBot/UTBotJava/actions/workflows/publish-plugin-and-cli.yml
- [x] Download plugin
- [x] Check downloaded zip-file size < 100 MB
- [x] Open IntelliJ IDEA 2022.2.2
- [x] Remove previously installed UTBot plugin
- [x] Clone or reuse UTBot project (https://github.com/UnitTestBot/UTBotJava.git)
- [x] Open the project in the IDE
- [x] Install the downloaded plugin

*Go through manual scenarios*

**Manual scenario #1**

- [x] Use default plugin settings
- [x] Open the utbot-sample/src/main/java/org/utbot/examples/algorithms/ArraysQuickSort.java file
- [x] Generate tests for the class
- [x] Remove results
- [x] Generate and Run test for a method
 
**Manual scenario #2**

- [x] Use default plugin settings
- [x] Open the utbot-sample/src/main/java/org/utbot/examples/mock/CommonMocksExample.java file
- [x] Generate tests with different Mocking options combinations
 
**Manual scenario #3**

- [x] Create a new Gradle project with JDK 17
- [x] Add a simple java file to test
- [x] Generate a test in the existing test root
 
**Manual scenario #4**

- [x] Create a new Maven project with JDK 8
- [x] Add a simple java file to test
- [x] Generate a test with a new test root

**Manual scenario #5**

- [x] Create a new Idea project with JDK 11
- [x] Add a simple java file to test
- [x] Generate tests for several classes

**Regression testing**

- [x] IDEA 2022.1.4 (JRE 11)
- [x] IDEA 2022.2.2 (JRE 17)
- [x] Sandbox
- [x] Nested calls
- [x] Recursion
- [x] Cycles
- [x] Mocks
- [x] UtUtils class generation
- [x] Summaries: tags, plain text
- [x] Summaries: regions
- [x] Exceptions: thrown, caught, check regions

**Comment by alisevych** [comment]
reproducing #1028

**Comment by alisevych** [comment]
new bug with Sandboxing and Fuzzing - many tests with same coverage are generated and no minimized

**Comment by alisevych** [comment]
reproducing #286

**Comment by alisevych** [comment]
new bug with Recursion - empty test class and 
java.lang.Exception
	at com.jetbrains.rd.util.LoggerKt.defaultLogFormat(Logger.kt:80)
	at org.utbot.rd.loggers.UtRdConsoleLogger.log(UtRdConsoleLogger.kt:24)
	at com.jetbrains.rd.util.SwitchLogger.log(Logger.kt:47)
	at org.utbot.instrumentation.instrumentation.et.RuntimeTraceStorage.visit(TraceHandler.kt:162)
	at org.utbot.examples.recursion.Recursion.fib(Recursion.java:21)
	at org.utbot.examples.recursion.Recursion.fib(Recursion.java:22)
	at org.utbot.examples.recursion.Recursion.fib(Recursion.java:22)
...

**Comment by alisevych** [comment]
reproduced #273  - please see the comment with stacktrace

**Comment by alisevych** [comment]
reproducing #711 - static field and static method

**Comment by alisevych** [comment]
new bug : sandboxed test is not compiling because commented stack trace contains "illegal unicode escape" in "jkmqh\uhauh"

**Comment by alisevych** [comment]
reproducing #1135

**Comment by alisevych** [comment]
new issue for Summaries: regions with Explicitly thrown exception region #1133

**Comment by alisevych** [comment]
reproducing #1141

**Comment by alisevych** [comment]
reproducing #1098  - on different code, when no tests are generated (timeout is minimal for example)

**Comment by alisevych** [comment]
proceeding with RC testing of [build#430](https://github.com/UnitTestBot/UTBotJava/actions/runs/3233979355)

*Check with different settings*
- [ ] JDK 17 - Gradle
- [ ] JDK 17 - Maven
- [ ] JDK 17 - IntelliJ
- [ ] existing test sources root
- [ ] new test sources root
- [ ] Test frameworks: JUnit 4, JUnit 5, TestNG
- [ ] Parametrized
- [ ] Mocks on / mock static off
- [ ] Mocks on / mock static on
- [ ]

**Comment by alisevych** [comment]
proceeding with RC testing of [build#434](https://github.com/UnitTestBot/UTBotJava/actions/runs/3235479235)

*Check with different settings*
- [x] JDK 17 - Gradle
- [x] JDK 17 - Maven
- [ ] JDK 17 - IntelliJ
- [ ] existing test sources root
- [ ] new test sources root
- [ ] Test frameworks: JUnit 4, JUnit 5, TestNG
- [ ] Parametrized
- [ ] Mocks on / mock static off
- [ ] Mocks on / mock static on

*Check other parts*

- [x] CLI, JDK 11
- [x] CLI, JDK 17
- [ ] CLI, JDK 8

*Environmental checks*

- [ ] macOs, last IDEA, JDK 17, 
- [ ] IDEA 2022.2.3 (new version 05-Oct-2022)

**Comment by alisevych** [comment]
new bug #1149  - reproducing on latest main

**Comment by alisevych** [comment]
IDEA dead lock -trying to save SARIF report - when resources folder is removed before generations

**Comment by alisevych** [comment]
new bug: test generated for StringExamples.isNotBlank has long string with 6000+ "\u0000"
