### ISSUE TITLE
RD threw ProtocolNotBoundException

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1213]
**Description**

ProtocolNotBoundException has fallen in IDEA on the latest main.

**To Reproduce**

1. IntelliJ Idea 2022.2.3
2. Gradle project with JDK 17 was opened
3. UTBot installed: [build from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/3296912146)
4. Generated tests for ArraysQuickSort class - copied from UTBotJava project

**Expected behavior**

No exception should be thrown in IDE.

**Actual behavior**

The following exception was thrown:
`com.jetbrains.rd.framework.base.ProtocolNotBoundException: Server.EngineProcessModel.obtainClassId::<<unbound>> is not bound to a protocol
`

**Visual proofs (screenshots, logs, images)**

~~~java
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 15:39:04.686 | Error | Lifetime                  | 152:ApplicationImpl pooled thread 20 | Lifetime `Anonymous` [Terminating, executing=0, resources=7]: exception on termination of resource: () -> kotlin.Unit | java.util.concurrent.CancellationException
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.jetbrains.rd.util.lifetime.RLifetimeKt.throwIfNotAlive(RLifetime.kt:523)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.process.EngineProcess.engineModel(EngineProcess.kt:105)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.process.EngineProcess.access$engineModel(EngineProcess.kt:57)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.process.EngineProcess$forceTermination$1.invokeSuspend(EngineProcess.kt:322)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.process.EngineProcess.forceTermination(EngineProcess.kt:320)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.process.EngineProcess$1.invoke(EngineProcess.kt:398)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.process.EngineProcess$1.invoke(EngineProcess.kt:397)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:427)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:408)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:431)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:408)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate$default(RLifetime.kt:375)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1.run(UtTestsDialogProcessor.kt:361)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-10-21 15:39:04,689 [ 898270]   INFO - STDOUT - 
2022-10-21 15:39:04,716 [ 898297] SEVERE - #c.i.o.p.Task - Server.EngineProcessModel.obtainClassId::<<unbound>> is not bound to a protocol
com.jetbrains.rd.framework.base.ProtocolNotBoundException: Server.EngineProcessModel.obtainClassId::<<unbound>> is not bound to a protocol
	at com.jetbrains.rd.framework.base.RdBindableBase.nb(RdBindableBase.kt:52)
	at com.jetbrains.rd.framework.base.RdBindableBase.getProtocol(RdBindableBase.kt:36)
	at com.jetbrains.rd.framework.impl.RdCall.createResponseScheduler(RdTask.kt:262)
	at com.jetbrains.rd.framework.impl.RdCall.startSuspending(RdTask.kt:256)
	at com.jetbrains.rd.framework.IRdCall$DefaultImpls.startSuspending(TaskInterfaces.kt:167)
	at com.jetbrains.rd.framework.impl.RdCall.startSuspending(RdTask.kt:184)
	at com.jetbrains.rd.framework.IRdCall$DefaultImpls.startSuspending$default(TaskInterfaces.kt:167)
	at org.utbot.intellij.plugin.process.EngineProcess$obtainClassId$1.invokeSuspend(EngineProcess.kt:208)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.intellij.plugin.process.EngineProcess.obtainClassId(EngineProcess.kt:207)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1$run$1$2.compute(UtTestsDialogProcessor.kt:170)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1$run$1$2.compute(UtTestsDialogProcessor.kt:168)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1.run(UtTestsDialogProcessor.kt:168)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-10-21 15:39:04,717 [ 898298] SEVERE - #c.i.o.p.Task - IntelliJ IDEA 2022.2.3  Build #IU-222.4345.14
2022-10-21 15:39:04,717 [ 898298] SEVERE - #c.i.o.p.Task - JDK: 17.0.4.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-10-21 15:39:04,717 [ 898298] SEVERE - #c.i.o.p.Task - OS: Windows 10
2022-10-21 15:39:04,718 [ 898299] SEVERE - #c.i.o.p.Task - Plugin to blame: UnitTestBot version: 2022.10.470.
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (JRE 17)
JDK 17

**Additional context**

No specific actions - a

**Comment by alisevych** [comment]
Same stacktrace as in 
- #1086

**Comment by SBOne-Kenobi** [comment]
Also, same exception #1183

**Comment by alisevych** [comment]
This issue depends on:
- #1118 
- #1347 
- #1359 
- #1392 
Verify it after previous ones after fix.
