### ISSUE TITLE
`Wrong number of type storages is provided, expected 1 arguments` at `TypeRegistry.saveObjectParameterTypeStorages`

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1668]
**Description**
Sometimes when I run ContestEngine over `spoon` project `Symbolic execution FAILED` happens due an exception `Wrong number of type storages is provided, expected 1 arguments, but only 2 found at org.utbot.engine.types.TypeRegistry.saveObjectParameterTypeStorages(TypeRegistry.kt:494)`

**To Reproduce**

It's not always happens but I've got it with following steps:

1. Open utbot project
2. Set filters on class and project in `org.utbot.contest.ContestEstimatorKt#main`:
```
methodFilter = "spoon.reflect.visitor.filter.LineFilter.*"
projectFilter = listOf("spoon-core-7.0.0")
```
3. I also set bigger than default timeout `val timeLimit = 300`
4. Start ContestEstimator 

**Expected behavior**

Test are generated without errors

**Actual behavior**
Even though some tests are generated there is exception in console output:

```
17:46:34.841 | ERROR | Symbolic execution FAILED
java.lang.IllegalArgumentException: Wrong number of type storages is provided, expected 1 arguments, but only 2 found
	at org.utbot.engine.types.TypeRegistry.saveObjectParameterTypeStorages(TypeRegistry.kt:494) ~[main/:?]
	at org.utbot.engine.Traverser.updateGenericTypeInfo(Traverser.kt:1168) ~[main/:?]
	at org.utbot.engine.Traverser.updateGenericTypeInfoFromMethod(Traverser.kt:1111) ~[main/:?]
	at org.utbot.engine.Traverser.commonInvokePart(Traverser.kt:2765) ~[main/:?]
	at org.utbot.engine.Traverser.virtualAndInterfaceInvoke(Traverser.kt:2590) ~[main/:?]
	at org.utbot.engine.Traverser.invokeResult(Traverser.kt:2452) ~[main/:?]
	at org.utbot.engine.Traverser.traverseInvokeStmt(Traverser.kt:1271) ~[main/:?]
	at org.utbot.engine.Traverser.traverseStmt(Traverser.kt:335) ~[main/:?]
	at org.utbot.engine.Traverser.traverse(Traverser.kt:312) ~[main/:?]
	at org.utbot.engine.UtBotSymbolicEngine$traverseImpl$1.invokeSuspend(UtBotSymbolicEngine.kt:301) [main/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_352]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
17:46:51.201 | ERROR | Symbolic execution FAILED 
... <<stack trace duplicated>>
...
17:47:22.348 | INFO  | Finished (in 81,199 sec): method spoon.reflect.visitor.filter.LineFilter.matches :: EXCEPTION :: 
<StatsForMethod> :
	#generatedTC=12
	FAILED 2 time(s) with 1 different exception(s)"
```

**Comment by CaelmBleidd** [comment]
Reproduced with following code: 
```kotlin
public class PathDependentGenericsExample {
    public int foo(GenericParent element) {
        if (element instanceof ClassWithOneGeneric) {
            functionWithOneGeneric((ClassWithOneGeneric<?>) element);
            return 1;
        }

        if (element instanceof ClassWithTwoGenerics) {
            functionWithTwoGenerics((ClassWithTwoGenerics<?, ?>) element);
            return 2;
        }

        return 3;
    }

    private <T> void functionWithOneGeneric(ClassWithOneGeneric<T> localVariable) {
        System.out.println();
    }

    private <T, A> void functionWithTwoGenerics(ClassWithTwoGenerics<T, A> assignment) {
        System.out.println();
    }
}

abstract class GenericParent {
}

class ClassWithOneGeneric<T> extends GenericParent {
}

class ClassWithTwoGenerics<T, A> extends GenericParent {
}

```
