### ISSUE TITLE
Unexpected NullPointerException in MockValueConstructor

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#1708]
**To Reproduce**

Run ContestEstimator with the following settings:

```
methodFilter = "com.google.common.collect.FilteredEntryMultimap.*
projectFilter = listOf("guava")
```

An unexpected exception occured. This problem is flacky, I reproduced it two times from approximately fifteen runs.

**Actual behavior**

**Comment by tyuldashev** [comment]
Similar exception in "antrlr" project
```
14:41:45.790 | INFO  | |> Starting concrete execution for remaining state: org.antlr.v4.semantics.UseDefAnalyzer.getRuleDependencies
14:41:46.151 | ERROR | Symbolic execution FAILED
org.utbot.instrumentation.util.InstrumentedProcessError: Error in the instrumented process |> com.jetbrains.rd.util.reactive.RdFault: Error during phase of constructing values from models, reason: org.utbot.instrumentation.instrumentation.execution.phases.ValueConstructionPhaseError: Error during phase of constructing values from models
	at org.utbot.instrumentation.instrumentation.execution.phases.ValueConstructionContext.wrapError(ValueConstructionContext.kt:29)
	at org.utbot.instrumentation.instrumentation.execution.phases.ValueConstructionContext.wrapError(ValueConstructionContext.kt:24)
	at org.utbot.instrumentation.instrumentation.execution.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:200)
	at org.utbot.instrumentation.instrumentation.execution.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:53)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:134)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:130)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1$1.invoke(ClientProcessUtil.kt:96)
	at org.utbot.rd.IdleWatchdog.wrapActive(ClientProcessUtil.kt:83)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1.invoke(ClientProcessUtil.kt:95)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:173)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:360)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at org.antlr.v4.tool.Rule.hashCode(Rule.java:316)
	at java.util.HashMap.hash(HashMap.java:340)
	at java.util.HashMap.put(HashMap.java:613)
	at java.util.HashSet.add(HashSet.java:220)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.utbot.common.KClassUtilKt.invokeCatching(KClassUtil.kt:11)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor$call$1.invoke(MockValueConstructor.kt:483)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor$call$1.invoke(MockValueConstructor.kt:482)
	at org.utbot.instrumentation.process.SecurityKt$runSandbox$1$1.invoke(Security.kt:38)
	at org.utbot.instrumentation.process.SecurityKt$sandbox$1.invoke(Security.kt:61)
	at org.utbot.instrumentation.process.SecurityKt$sandbox$2.invoke(Security.kt:77)
	at org.utbot.instrumentation.process.SecurityKt$sandbox$3.invoke(Security.kt:82)
	at org.utbot.instrumentation.process.SecurityKt$sandbox$4.run(Security.kt:88)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.utbot.instrumentation.process.SecurityKt.sandbox(Security.kt:88)
	at org.utbot.instrumentation.process.SecurityKt.sandbox(Security.kt:82)
	at org.utbot.instrumentation.process.SecurityKt.sandbox(Security.kt:77)
	at org.utbot.instrumentation.process.SecurityKt.sandbox(Security.kt:61)
	at org.utbot.instrumentation.process.SecurityKt.runSandbox(Security.kt:38)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor.call(MockValueConstructor.kt:482)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor.updateWithExecutableCallModel(MockValueConstructor.kt:425)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor.constructFromAssembleModel(MockValueConstructor.kt:375)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor.construct(MockValueConstructor.kt:136)
	at org.utbot.instrumentation.instrumentation.execution.constructors.MockValueConstructor.constructMethodParameters(MockValueConstructor.kt:111)
	at org.utbot.instrumentation.instrumentation.execution.phases.ValueConstructionContext.constructParameters(ValueConstructionContext.kt:39)
	at org.utbot.instrumentation.instrumentation.execution.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:93)
	... 18 more
```

**Comment by alisevych** [comment]
Reproducing on `guava` library for `com.google.common.io.Closeables.close` method
