### ISSUE TITLE
UTBot cannot generate tests for CherryPy app due usage of decorators: `Selected method is not a function definition`

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#1821]
**Description**

When trying to generate test for [CherryPy](https://docs.cherrypy.dev/en/latest/) application UTBot fails with exception.

**To Reproduce**

```python
import cherrypy

class HelloWorld(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"
```

1. Use code above to reproduce
2. Install cherrypy if needed
3. Invoke test generation for `index` function

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

No tests are generated, exception is thrown.

**Visual proofs (screenshots, logs, images)**

```
java.lang.IllegalStateException: Selected method is not a function definition
	at org.utbot.python.PythonTestCaseGenerator.findMethodByDescription(PythonTestCaseGenerator.kt:59)
	at org.utbot.python.PythonTestCaseGenerator.generate(PythonTestCaseGenerator.kt:98)
	at org.utbot.python.PythonTestGenerationProcessor.processTestGeneration(PythonTestGenerationProcessor.kt:109)
	at org.utbot.python.PythonTestGenerationProcessor.processTestGeneration$default(PythonTestGenerationProcessor.kt:32)
	at org.utbot.intellij.plugin.language.python.PythonDialogProcessor$createTests$1.run(PythonDialogProcessor.kt:171)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tochilinak** [comment]
For now we didn't plan to support decorated functions (except maybe staticmethod or classmethod). We can add test generation for cases when decorators are annotated (for example, Flask decorators), but that is not the case for CherryPy.

**Comment by tyuldashev** [comment]
Dedicated feature enhancement entered #1849 to support that functionality in the future.
