### ISSUE TITLE
JS. `utbot.TimeoutException` thrown from JsDialogProcessor

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1944]
**Description**

_Example:_ There are hundreds of error messages in the UTBot log. Looks like the problem is in the concrete executor.

**To Reproduce**

1. [Install the latest IU plugin built from unit-test-bot/rc3102023 branch in IntelliJ Idea Ultimate 2022.2.4](https://github.com/UnitTestBot/UTBotJava/actions/runs/4408022896) - take **`utbot-intellij-IU-2023.3.*`** artefact 
2. Open JavaScript project with already installed requirements
3. Copy samples folder from `utbot-js` module and paste it into this project
4. Open `samples/arrays.js` in Project view, place cursor in `ObjectParameter`, call Alt+Shift+U
5. Start test generation for `performAction` with default settings

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

`org.utbot.framework.plugin.api.TimeoutException` is thrown from `org.utbot.intellij.plugin.language.js.JsDialogProcessor$createTests$1.run(JsDialogProcessor.kt:186)`

**Visual proofs (screenshots, logs, images)**

Stacktrace:
~~~kotlin
org.utbot.framework.plugin.api.TimeoutException: 
	at utils.JsCmdExec.runCommand(JsCmdExec.kt:27)
	at utils.JsCmdExec.runCommand$default(JsCmdExec.kt:10)
	at service.TernService.installDeps(TernService.kt:81)
	at service.TernService.<init>(TernService.kt:73)
	at api.JsTestGenerator.run(JsTestGenerator.kt:108)
	at org.utbot.intellij.plugin.language.js.JsDialogProcessor$createTests$1.run(JsDialogProcessor.kt:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
~~~

**Environment**

Windows 10 Pro
Node.js 18.14.2

**Additional context**

To check it's reproducible

**Comment by alisevych** [comment]
> 

Please compare main and unit-test-bot/rc3102023
and check if some changes for JS are missing

**Comment by alisevych** [comment]
Will generate plugin with them and retest all the bugs.

**Comment by alisevych** [comment]
#### Not reproducing
on fresh version of unit-test-bot/rc3102023 branch. IU-plugin from this run:
https://github.com/UnitTestBot/UTBotJava/actions/runs/4434721564
The last commit for this run was dccfdade.
