### ISSUE TITLE
ComboBoxWithSeparators error in IDEA 2023.1 for Spring project

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2103]
**Description**

com.intellij.diagnostic.PluginException...
  error: com/intellij/openapi/roots/ui/configuration/ComboBoxWithSeparators,

from `GenerateTestsDialogWindow.createComboBoxWithSeparatorsForSpringConfigs`

**To Reproduce**

1. Run the 'spring-petclinic' (gradle) project in IntelliJ Idea Ultimate 2023.1
2. Install UnitTestBot -IU- plugin [built from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/4616516699)
3. Call UnitTestBot action on BaseEntity Java-class (Alt+Shift+U)

**Expected behavior**

UnitTestBot Test generation dialog should be opened.
It works fine in IDEA 2022.3.3

**Actual behavior**

PluginException from `GenerateTestsDialogWindow.createComboBoxWithSeparatorsForSpringConfigs`
is thrown down into IDE

**Visual proofs (screenshots, logs, images)**

~~~java
com.intellij.diagnostic.PluginException: Cannot load class org.utbot.intellij.plugin.ui.GenerateTestsDialogWindow$createComboBoxWithSeparatorsForSpringConfigs$comboBox$1 (
  error: com/intellij/openapi/roots/ui/configuration/ComboBoxWithSeparators,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=UnitTestBot, id=org.utbot.intellij.plugin.id, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\utbot-intellij, version=2023.4.4191., package=null, isBundled=false), packagePrefix=null, instanceId=424, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:325)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:172)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.utbot.intellij.plugin.ui.GenerateTestsDialogWindow.createComboBoxWithSeparatorsForSpringConfigs(GenerateTestsDialogWindow.kt:248)
	at org.utbot.intellij.plugin.ui.GenerateTestsDialogWindow.createComboBoxWithSeparatorsForSpringConfigs$default(GenerateTestsDialogWindow.kt:244)
	at org.utbot.intellij.plugin.ui.GenerateTestsDialogWindow.<init>(GenerateTestsDialogWindow.kt:203)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialog(UtTestsDialogProcessor.kt:137)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialogAndGenerateTests(UtTestsDialogProcessor.kt:101)
	at org.utbot.intellij.plugin.language.JvmLanguageAssistant.actionPerformed(JavaLanguage.kt:42)
	at org.utbot.intellij.plugin.ui.actions.GenerateTestsAction.actionPerformed(GenerateTestsAction.kt:11)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:598)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/roots/ui/configuration/ComboBoxWithSeparators
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:112)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:233)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:183)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:320)
	... 44 more
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.roots.ui.configuration.ComboBoxWithSeparators PluginClassLoader(plugin=PluginDescriptor(name=UnitTestBot, id=org.utbot.intellij.plugin.id, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\utbot-intellij, version=2023.4.4191., package=null, isBundled=false), packagePrefix=null, instanceId=424, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 52 more
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2023.1

**Additional context**

Issue is present in the latest IDEA only.

**Comment by Vassiliy-Kudryashov** [comment]
The issue seems to be fixed within #2109
