### ISSUE TITLE
Allow to use JAR files in classpatch during CLI test generation

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#2343]
**Description**

Currently when using CLI UTBot user has to specify folder which contains compiled classes of app under test. It would be convenient if it also accept JAR files. Currently it cannot and fails with error (see the exception and steps to reproduce at the end of the issue).

_Example:_ I'm running UTBot over public libraries like Guava, which have source code and compiled JAR available, but compilation process could be cumbersome and time consuming, so it would be helpful if I can supply JAR directly to the UTBot.

**Expected behavior**

--classpath (-cp) accepts path to JAR files.

**Potential alternatives**

Currently I have to manually unzip JAR file and point UTBot to folder with unpacked classes.

**Steps to reproduce**
1. Download UTBot CLI, use this action to build it if needed - https://github.com/UnitTestBot/UTBotJava/actions/workflows/publish-cli-from-branch.yml
2. Download and unpack attached project, it contains one source file and JAR build from that source [calc.zip](https://github.com/UnitTestBot/UTBotJava/files/11906633/calc.zip)
3. Run CLI with command `/java -jar utbot-cli-pele-2023.6.1.jar generate --classpath ./calc.jar --source ./Calc.java --output ./test/Calc.java org.test.Calc`
4. Exception is thrown
```java
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
16:54:32.050 | ERROR | withUtContext | java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/utbot/jazzer/pdfbox/utbot/file
16:54:32.054 | ERROR | GenerateTestsCommand | An error has occurred while generating test for snippet org.test.Calc : java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/utbot/jazzer/pdfbox/utbot/file
java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/utbot/jazzer/pdfbox/utbot/file
        at soot.asm.AllInMemoryClassProvider.<init>(AllInMemoryClassProvider.java:61)
        at soot.SourceLocator.setupClassProviders(SourceLocator.java:272)
        at soot.SourceLocator.getClassSource(SourceLocator.java:214)
        at soot.Scene.tryLoadClass(Scene.java:978)
        at soot.Scene.loadBasicClasses(Scene.java:1830)
        at soot.Scene.loadNecessaryClasses(Scene.java:1949)
        at org.utbot.framework.util.SootUtilsKt.initSoot(SootUtils.kt:90)
        at org.utbot.framework.util.SootUtilsKt.access$initSoot(SootUtils.kt:1)
        at org.utbot.framework.util.SootUtils.runSoot(SootUtils.kt:45)
        at org.utbot.framework.plugin.api.TestCaseGenerator.<init>(TestCaseGenerator.kt:107)
        at org.utbot.framework.plugin.api.TestCaseGenerator.<init>(TestCaseGenerator.kt:62)
        at org.utbot.cli.GenerateTestsAbstractCommand.initializeGenerator(GenerateTestsAbstractCommand.kt:201)
        at org.utbot.cli.GenerateTestsCommand.run(GenerateTestsCommand.kt:105)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
        at org.utbot.cli.ApplicationKt.main(Application.kt:31)
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/utbot/jazzer/pdfbox/utbot/file
        at soot.asm.AllInMemoryClassProvider.loadDir(AllInMemoryClassProvider.java:108)
        at soot.asm.AllInMemoryClassProvider.load(AllInMemoryClassProvider.java:84)
        at soot.asm.AllInMemoryClassProvider.<init>(AllInMemoryClassProvider.java:57)
        ... 20 more
Caused by: java.nio.file.NoSuchFileException: /home/utbot/jazzer/pdfbox/utbot/file
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.walk(Files.java:3918)
        at java.base/java.nio.file.Files.walk(Files.java:3973)
        at soot.asm.AllInMemoryClassProvider.loadDir(AllInMemoryClassProvider.java:93)
        ... 22 more
```

**Comment by tyuldashev** [comment]
A bit different exception on Windows:
```java
D:\utbot\projects\calc\utbot>"C:\Program Files\Amazon Corretto\jdk17.0.4_9\bin\java.exe"  -jar utbot-cli-2023.06-SNAPSHOT.jar generate -cp .\build\calc.jar --source .\Calc.java --output .\test\Calc.java org.test.Calc
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.nio.file.InvalidPathException: Illegal char <:> at index 33: D:/utbot/projects/calc/utbot/file:/D:/utbot/projects/calc/utbot/./build/calc.jar!/
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.utbot.cli.GenerateTestsAbstractCommand.getWorkingDirectory(GenerateTestsAbstractCommand.kt:150)
        at org.utbot.cli.GenerateTestsCommand.run(GenerateTestsCommand.kt:90)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
        at org.utbot.cli.ApplicationKt.main(Application.kt:31)

D:\utbot\projects\calc\utbot>
```
