### ISSUE TITLE
Test generation fails with `NoSuchFieldError: Companion` from `UtTestsDialogProcessor`

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2474]
**Description**

Test generation fails with `NoSuchFieldError: Companion` from `UtTestsDialogProcessor`

**To Reproduce**

1. Install [UnitTestBot plugin with Spring support for IU](https://github.com/UnitTestBot/UTBotJava/actions/runs/5740046634) in IntelliJ IDEA Ultimate 2023.1 (not the latest)

![image](https://github.com/UnitTestBot/UTBotJava/assets/37301492/f962afb1-ab7d-4b69-8616-85f5174e7466)

2. Open `UTBotJava` project
3. Generate tests for a class with default settings

**Expected behavior**

No exception is expected to be thrown down into IDE.

**Actual behavior**

Exception from UtTestsDialogProcessor is thrown down into IDE.
Test generation fails.

**Screenshots, logs**

~~~java
java.lang.NoSuchFieldError: Companion
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1$run$3$2.invoke(UtTestsDialogProcessor.kt:319)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1$run$3$2.invoke(UtTestsDialogProcessor.kt:315)
	at org.utbot.intellij.plugin.process.EngineProcess.executeWithTimeoutSuspended(EngineProcess.kt:436)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$1$1.run(UtTestsDialogProcessor.kt:315)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
~~~

**Environment**

IntelliJ IDEA version - 2023.1 Ultimate
Project - Maven/Gradle
JDK - 11/17

**Additional context**

reproducing for Spring also (Medical-Web-App)

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov 
When you tried to reproduce, which ideVersion have you set in gradle.properties?
Have you changed ideType to IU?

**Comment by alisevych** [comment]
@Vassiliy-Kudryashov 
Seems that the issue cannot be reproduced in debug IDE.
The version conflict seems to be as following: plugin is built with ideVersion=232.* and then installed into ide 231.*
