### ISSUE TITLE
`NoSuchElementException: List is empty.` during fuzzing `samples.Integers` 

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#2511]
**Description**
Exception `NoSuchElementException` is thrown during test generation with fuzzer.

**To Reproduce**

1. Install UnitTestBot plugin built from main in IntelliJ IDEA
2. Set Fuzzing = 100%
3. Generate tests for code below with `No mocks` option

```java
    // copied from org.utbot.fuzzing.samples.Integers#diff
    public static void diff(int a) {
        a = Math.abs(a);
        while (a > 0) {
            a = a % 2;
        }
        if (a < 0) {
            throw new IllegalArgumentException();
        }
        throw new RuntimeException();
    }
```

**Expected behavior**
Tests are generated without errors.

**Actual behavior**
Sometimes tests are generated, but they always contain following error:
```java
    public void testDiff_errors() {
        // Couldn't generate some tests. List of errors:
        //
        // 1 occurrences of:
        // List is empty.

    }
```

**Screenshots, logs**
`utbot-engine-current.log` :

~~~java
14:02:56.737 | WARN  | CgAbstractTestClassConstructor | Code generation error
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:418) ~[kotlin-stdlib-1.8.10.jar:1.8.10-release-430(1.8.10)]
	at org.utbot.framework.codegen.services.access.CgCallableAccessManagerImpl.canBeArgsOf(CgCallableAccessManager.kt:284) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.services.access.CgCallableAccessManagerImpl.canBeCalledWith(CgCallableAccessManager.kt:317) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.services.access.CgCallableAccessManagerImpl.invoke(CgCallableAccessManager.kt:116) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.invoke(CgMethodConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$constructExceptionProducingBlock$1.invoke(CgMethodConstructor.kt:406) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$constructExceptionProducingBlock$1.invoke(CgMethodConstructor.kt:403) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$processExecutionFailure$2.invoke(CgMethodConstructor.kt:352) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$processExecutionFailure$2.invoke(CgMethodConstructor.kt:351) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.services.framework.Junit5Manager$expectTimeout$lambda$1.invoke(TestFrameworkManager.kt:510) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.services.framework.Junit5Manager$expectTimeout$lambda$1.invoke(TestFrameworkManager.kt:510) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$block$1.invoke(CgContext.kt:260) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$block$1.invoke(CgContext.kt:259) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.withNameScope(CgContext.kt:365) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withNameScope(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.block(CgContext.kt:259) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.block(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgStatementConstructorImpl.block(CgStatementConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgStatementConstructorImpl$lambda$1.invoke(CgStatementConstructor.kt:400) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgStatementConstructorImpl$lambda$1.invoke(CgStatementConstructor.kt:395) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.withNameScope(CgContext.kt:365) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withNameScope(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgStatementConstructorImpl.withNameScope(CgStatementConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgStatementConstructorImpl.lambda(CgStatementConstructor.kt:395) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.services.framework.Junit5Manager.expectTimeout(TestFrameworkManager.kt:510) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.processExecutionFailure(CgMethodConstructor.kt:351) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.generateResultAssertions(CgMethodConstructor.kt:331) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$createTestMethod$1$2$mainBody$1.invoke(CgMethodConstructor.kt:1481) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$createTestMethod$1$2$mainBody$1.invoke(CgMethodConstructor.kt:1461) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$createTestMethod$1$2.invoke(CgMethodConstructor.kt:1498) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$createTestMethod$1$2.invoke(CgMethodConstructor.kt:1449) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$block$1.invoke(CgContext.kt:260) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$block$1.invoke(CgContext.kt:259) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.withNameScope(CgContext.kt:365) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withNameScope(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.block(CgContext.kt:259) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.block(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.block(CgMethodConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$testMethod$testMethod$1.invoke(CgMethodConstructor.kt:1947) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$testMethod$testMethod$1.invoke(CgMethodConstructor.kt:1944) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.BuildersKt.buildTestMethod(Builders.kt:110) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.testMethod(CgMethodConstructor.kt:1944) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.testMethod$default(CgMethodConstructor.kt:1903) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$createTestMethod$1.invoke(CgMethodConstructor.kt:1449) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor$createTestMethod$1.invoke(CgMethodConstructor.kt:1442) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.withTestMethodScope(CgMethodConstructor.kt:1817) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgMethodConstructor.createTestMethod(CgMethodConstructor.kt:1442) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$createTest$1.invoke(CgAbstractTestClassConstructor.kt:105) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$createTest$1.invoke(CgAbstractTestClassConstructor.kt:104) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.withExecutionIdScope(CgContext.kt:288) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withExecutionIdScope(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor.withExecutionIdScope(CgAbstractTestClassConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor.createTest(CgAbstractTestClassConstructor.kt:104) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor.constructTestSet(CgSimpleTestClassConstructor.kt:94) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor$constructTestClassBody$1$2.invoke(CgSimpleTestClassConstructor.kt:55) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor$constructTestClassBody$1$2.invoke(CgSimpleTestClassConstructor.kt:54) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContextOwner$DefaultImpls.withTestSetIdScope(CgContext.kt:283) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withTestSetIdScope(CgContext.kt:480) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor.withTestSetIdScope(CgAbstractTestClassConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor$constructTestClassBody$1.invoke(CgSimpleTestClassConstructor.kt:54) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor$constructTestClassBody$1.invoke(CgSimpleTestClassConstructor.kt:30) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.BuildersKt.buildClassBody(Builders.kt:75) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor.constructTestClassBody(CgSimpleTestClassConstructor.kt:30) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgSimpleTestClassConstructor.constructTestClassBody(CgSimpleTestClassConstructor.kt:27) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$constructTestClass$1.invoke(CgAbstractTestClassConstructor.kt:72) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$constructTestClass$1.invoke(CgAbstractTestClassConstructor.kt:63) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.BuildersKt.buildClass(Builders.kt:64) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor.constructTestClass(CgAbstractTestClassConstructor.kt:63) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$construct$1$1.invoke(CgAbstractTestClassConstructor.kt:54) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$construct$1$1.invoke(CgAbstractTestClassConstructor.kt:54) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withTestClassScope(CgContext.kt:585) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor.withTestClassScope(CgAbstractTestClassConstructor.kt) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$construct$1.invoke(CgAbstractTestClassConstructor.kt:54) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor$construct$1.invoke(CgAbstractTestClassConstructor.kt:53) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.BuildersKt.buildClassFile(Builders.kt:49) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.tree.CgAbstractTestClassConstructor.construct(CgAbstractTestClassConstructor.kt:53) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.CodeGenerator.generate(CodeGenerator.kt:17) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator$generateAsStringWithTestReport$1$1.invoke(AbstractCodeGenerator.kt:48) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator$generateAsStringWithTestReport$1$1.invoke(AbstractCodeGenerator.kt:47) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.domain.context.CgContext.withTestClassFileScope(CgContext.kt:575) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator$generateAsStringWithTestReport$1.invoke(AbstractCodeGenerator.kt:47) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator$generateAsStringWithTestReport$1.invoke(AbstractCodeGenerator.kt:46) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator.withCustomContext(AbstractCodeGenerator.kt:75) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator.generateAsStringWithTestReport(AbstractCodeGenerator.kt:46) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.codegen.generator.AbstractCodeGenerator.generateAsStringWithTestReport$default(AbstractCodeGenerator.kt:41) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.process.EngineProcessMainKt$setup$5.invoke(EngineProcessMain.kt:156) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.framework.process.EngineProcessMainKt$setup$5.invoke(EngineProcessMain.kt:153) ~[utbot-framework-2023.8.5058.jar:?]
	at org.utbot.rd.IdleWatchdog$measureTimeForActiveCall$1$2$1.invoke(ClientProcessUtil.kt:115) ~[utbot-rd-2023.8.5058.jar:?]
	at org.utbot.rd.IdleWatchdog.wrapActive(ClientProcessUtil.kt:88) ~[utbot-rd-2023.8.5058.jar:?]
	at org.utbot.rd.IdleWatchdog$measureTimeForActiveCall$1.invoke(ClientProcessUtil.kt:114) ~[utbot-rd-2023.8.5058.jar:?]
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:362) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54) ~[rd-framework-2023.1.2.jar:?]
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda-3(SingleThreadScheduler.kt:41) ~[rd-core-2023.1.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
~~~

**Environment**

IntelliJ IDEA version - 2023.2
Project - utbot or just copy sample to any other Java project
Plugin - 2023.8.5058

**Additional context**
There is no such error in 2023.1.5 with plugin from latest release 2023.3, so that's regression error.

**Comment by IlyaMuravjov** [comment]
@tyuldashev can you recheck that it reproduces on `main`?

**Comment by tyuldashev** [comment]
@IlyaMuravjov that's latest available main - https://github.com/UnitTestBot/UTBotJava/actions/runs/5855298041

**Comment by IlyaMuravjov** [comment]
> @IlyaMuravjov that's latest available main - https://github.com/UnitTestBot/UTBotJava/actions/runs/5855298041

Then wait for #2506 to get published, it was merged an hour ago.

**Comment by tyuldashev** [comment]
Resolved in latest builds, checked with [5065](https://github.com/UnitTestBot/UTBotJava/actions/runs/5865777567)
