### ISSUE TITLE
ClassNotFoundException with Unsafe on generating tests for EnumMap

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#417]
**Description**

Test generation fails for EnumMap. The following exception is shown in tests:
Error in the child process |> java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe

**To Reproduce**

1. IntelliJ IDEA with UTBotJava plugin installed
2. A project with JDK 8/11 is opened
3. Add the following class:

```
public class MapWithEnum {

    public void createEnumMap() {
        Map<WorkDays, Integer> map = new EnumMap<>(WorkDays.class);
        map.put(WorkDays.Monday, 125);
        map.put(WorkDays.Tuesday, 31);
        map.put(3, WorkDays.Friday);
        map.remove(4);
    }

 public enum WorkDays {
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday
    }
}
```

4. Generate tests for the method

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

An error test is generated with information about error in child process

**Visual proofs (screenshots, logs, images)**

~~~
public void testCreateEnumMap_errors() {
        // Couldn't generate some tests. List of errors:
        // 
        // 6 occurrences of:
        /* Error in the child process |> java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
        		at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        		at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        		at org.utbot.instrumentation.process.HandlerClassesLoader.loadClass(ChildProcess.kt:38)
        		at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        		at org.utbot.framework.concrete.MockValueConstructor.kClass(MockValueConstructor.kt:470)
        		at org.utbot.framework.concrete.MockValueConstructor.javaClass(MockValueConstructor.kt:455)
        		at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:158)
        		at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:127)
        		at org.utbot.framework.concrete.MockValueConstructor.constructStatics(MockValueConstructor.kt:110)
        		at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:146)
        		at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:107)
        		at org.utbot.instrumentation.process.ChildProcessKt.loop(ChildProcess.kt:133)
        		at org.utbot.instrumentation.process.ChildProcessKt.main(ChildProcess.kt:77)
        		at org.utbot.instrumentation.process.ChildProcessKt.main(ChildProcess.kt)
        	 */

    }
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.3
checked on JDK 8 and 11 - same error
[UTBotJava plugin build from here](https://github.com/UnitTestBot/UTBotJava/actions/runs/2612161368)

**Comment by sergeypospelov** [comment]
It caused by the different JDKs, which is analyzed by Engine and on which Child Process runs.

**Comment by dtim** [comment]
This issue may be related to #884.
