### ISSUE TITLE
RuntimeException in IDEA from UnitTestBot plugin: can't find Object at getSootClass

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#443]
**Description**

RuntimeException in IDEA from UnitTestBot plugin: can't find Object at getSootClass

**To Reproduce**

1. Open IntelliJ IDEA
2. Plugin is installed
3. UTBotJava project is opened
4. Start test generation for ArrayQuickSort
5. Create a new project with JDK 11

**Expected behavior**

No exceptions are supposed to be

**Actual behavior**

RuntimeException is thrown with the following stacktrace:

java.lang.RuntimeException: 
Aborting: can't find classfile java.lang.Object
	at soot.Scene.getSootClass(Scene.java:1176)
	at org.utbot.engine.TypeResolverKt.getOBJECT_TYPE(TypeResolver.kt:316)
	at org.utbot.engine.ExtensionsKt.isJavaLangObject(Extensions.kt:134)
	at org.utbot.engine.pc.Z3TranslatorVisitor.filterInappropriateTypes(Z3TranslatorVisitor.kt:210)
	at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:165)
	at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35)
	at org.utbot.engine.pc.UtIsExpression.accept(UtExpression.kt:349)
	at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49)
	at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:107)
	at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35)
	at org.utbot.engine.pc.UtOrBoolExpression.accept(UtExpression.kt:721)
	at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49)
	at org.utbot.engine.pc.UtSolver.check(UtSolver.kt:228)
	at org.utbot.engine.selectors.BasePathSelector.checkUnsat(BasePathSelector.kt:64)
	at org.utbot.engine.selectors.BasePathSelector.checkUnsatIfFork(BasePathSelector.kt:70)
	at org.utbot.engine.selectors.BasePathSelector.poll(BasePathSelector.kt:83)
	at org.utbot.engine.UtBotSymbolicEngine$traverseImpl$1.invokeSuspend(UtBotSymbolicEngine.kt:509)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator$generateForSeveralMethods$4.invoke(UtBotTestCaseGenerator.kt:282)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator$generateForSeveralMethods$4.invoke(UtBotTestCaseGenerator.kt:56)
	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator.generateForSeveralMethods(UtBotTestCaseGenerator.kt:281)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator.generateForSeveralMethods$default(UtBotTestCaseGenerator.kt:268)
	at org.utbot.intellij.plugin.generator.CodeGenerator.generateForSeveralMethods(CodeGenerator.kt:55)
	at org.utbot.intellij.plugin.ui.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:177)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.3
JDK 8, 11
Plugin used: https://github.com/UnitTestBot/UTBotJava/actions/runs/2622387470

**Additional context**

In one case reproducing [IndexNotReadyException ](#273) and PluginException from Java plugin are also thrown.

**Comment by alisevych** [comment]
@CaelmBleidd 
Reproduced again:

**Steps performed**

1. IDEA Ultimate 2022.1.3 was opened with plugin got from here: https://github.com/UnitTestBot/UTBotJava/actions/runs/2669070529
2. Gradle project with JDK 8 was opened
3. Gradle project with JDK 11 was opened
4. Test generation was started in One window
5. Then - before it was finished - started in another window

**Comment by alisevych** [comment]
@CaelmBleidd Could you please consider the stacktrace whether the root cause can be found and fixed? Or we need to close the bug as not relevant any more?

**Comment by CaelmBleidd** [comment]
I'm afraid that I cannot at the moment determine the reason for the error by the stack trace (and I couldn't reproduce it). Perhaps, it'd be better to close the bug till the next occasion
