### ISSUE TITLE
Test generation fails for test with Queue as method parameter

### ISSUE THREAD

**Issue by tochilinak** [UnitTestBot/UTBotJava#524]
**Description**

Test generation fails for test with Queue as method parameter.

**To Reproduce**

1. Open project in IntelliJ Idea with one of the latest versions of UTBotJava plugin installed
2. Add a class
3. Add a class method:
    `public boolean q(Queue<Integer> a) { return a.add(1); }`
4. Generate test for this method

**Expected behavior**

Tests are supposed to be generated.

**Actual behavior**

An error occurs: ClassNotFoundException.

**Visual proofs (screenshots, logs, images)**

```
org.utbot.instrumentation.util.ChildProcessError: Error in the child process |> java.lang.ClassNotFoundException: java.lang.invoke.VarHandleObjects$FieldInstanceReadWrite
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.utbot.instrumentation.process.HandlerClassesLoader.loadClass(ChildProcess.kt:38)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.utbot.framework.concrete.MockValueConstructor.kClass(MockValueConstructor.kt:470)
	at org.utbot.framework.concrete.MockValueConstructor.javaClass(MockValueConstructor.kt:455)
	at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:158)
	at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:127)
	at org.utbot.framework.concrete.MockValueConstructor.constructStatics(MockValueConstructor.kt:110)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:145)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:106)
	at org.utbot.instrumentation.process.ChildProcessKt.loop(ChildProcess.kt:133)
	at org.utbot.instrumentation.process.ChildProcessKt.main(ChildProcess.kt:77)
	at org.utbot.instrumentation.process.ChildProcessKt.main(ChildProcess.kt)

	at org.utbot.instrumentation.ConcreteExecutor.executeAsync(ConcreteExecutor.kt:415)
	at org.utbot.instrumentation.ConcreteExecutor$executeAsync$1.invokeSuspend(ConcreteExecutor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:158)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:51)
	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate(TestCaseGenerator.kt:157)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate$default(TestCaseGenerator.kt:144)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: java.lang.invoke.VarHandleObjects$FieldInstanceReadWrite
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.utbot.instrumentation.process.HandlerClassesLoader.loadClass(ChildProcess.kt:38)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.utbot.framework.concrete.MockValueConstructor.kClass(MockValueConstructor.kt:470)
	at org.utbot.framework.concrete.MockValueConstructor.javaClass(MockValueConstructor.kt:455)
	at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:158)
	at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:127)
	at org.utbot.framework.concrete.MockValueConstructor.constructStatics(MockValueConstructor.kt:110)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:145)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:106)
	at org.utbot.instrumentation.process.ChildProcessKt.loop(ChildProcess.kt:133)
	at org.utbot.instrumentation.process.ChildProcessKt.main(ChildProcess.kt:77)
	at org.utbot.instrumentation.process.ChildProcessKt.main(ChildProcess.kt)
```

**Environment**

Ubuntu, Java 8, guest IDEA 2020.2 community

**Additional context**

Same code fails on https://www.utbot.org/utbot/.

Error:
```
Status Code: TEST_GENERATION_FAILED

TEST GENERATION: TEST_GENERATION_FAILED
Timeout

TEST RUN: ERROR OCCURRED
[object Object]: no details
```

**Comment by dtim** [comment]
The `java.lang.invoke.VarHandleObjects` class was introduced in JDK 9. It seems that this bug is related to the JDK mismatch. I suppose this exception may occur when the project is compiled with JDK 11 and the child process is run by the concrete executor with JDK 8. On the other hand, this hypothesis contradicts the environment mentioned in the issue (Java 8).

@tochilinak, @alisevych could you please clarify a bit the environment where this exception is thrown (IDEA runtime version, project JDK, source and test modules JDK)?

**Comment by alisevych** [comment]
FYI @denis-fokin @Vassiliy-Kudryashov 
**Additional context**
When the process of test generation is hanging - plugin deinstallation is hanging too:
![524 IDEA hanging](https://user-images.githubusercontent.com/37301492/179461941-16c50f62-b022-4f3a-a16b-17480346d6db.jpg)
When the corresponding java process is killed - the following exception is shown in IDEA:
```
java.util.NoSuchElementException
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:377)
	at org.utbot.instrumentation.ConcreteExecutorPool.close(ConcreteExecutor.kt:403)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate(TestCaseGenerator.kt:217)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate$default(TestCaseGenerator.kt:144)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by alisevych** [comment]
@dtim 
There are different behaviors for projects with JDK 8 and JDK 11.

**IDEA**

IntelliJ IDEA 2022.1.3 (Ultimate Edition)
Build #IU-221.5921.22, built on June 21, 2022
Licensed to Huawei Technologies Co., Ltd

Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    org.utbot.intellij.plugin.id (2022.7)

Kotlin: 221-1.6.21-release-337-IJ5921.22

**JDKs**

1. Gradle project with JDK 8

org.utbot.instrumentation.util.ChildProcessError: Error in the child process |> java.lang.ClassNotFoundException: java.lang.invoke.VarHandleObjects$FieldInstanceReadWrite

full stacktrace in the initial bug description

2. Gradle project with JDK 11

process is hanging
kill the java process => java.util.NoSuchElementException from ConcreteExecutor 
please see the previous comment ↥

**Comment by alisevych** [comment]
@dtim 

**Additional context **

IDEA 2022.1.3 JBR 11 Plugin [installed from here](https://github.com/UnitTestBot/UTBotJava/actions/runs/2669070529)

Project with JDK 11
Method with Queue<Integer> parameter
Test generation is started
+ Wait while it's hanging
+ Kill corresponding java process in Process Explorer

**Actual behavior**

Test class is generated

**Comment by alisevych** [comment]
**Additional context**

Site backend was updated today.
The error displayed now - on utbot.org -  for the same code - is different from the one before:
it has the stacktrace in statusDetails:

```
09:28:01.659 | INFO  | AllInMemoryClassProvider | Loaded: 3 path entries, 19929 classes, 62321900 bytes
09:28:02.575 | INFO  | TestCaseGenerator | |> Resuming method Solution.q(Queue)
09:28:02.934 | ERROR | GenerateTestsCommand | An error has occurred while generating test for snippet Solution : java.lang.NullPointerException: member.declaringClass.`package` must not be null
java.lang.NullPointerException: member.declaringClass.`package` must not be null
	at org.utbot.fuzzer.providers.ObjectModelProvider$Companion.isAccessible(ObjectModelProvider.kt:156)
	at org.utbot.fuzzer.providers.ObjectModelProvider$Companion.access$isAccessible(ObjectModelProvider.kt:145)
	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1$invokeSuspend$$inlined$with$lambda$1$1.invoke(ObjectModelProvider.kt:76)
	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1$invokeSuspend$$inlined$with$lambda$1$1.invoke(ObjectModelProvider.kt:37)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
	at kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:603)
	at kotlin.sequences.TakeSequence$iterator$1.<init>(Sequences.kt:411)
	at kotlin.sequences.TakeSequence.iterator(Sequences.kt:409)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$2.invoke(_Sequences.kt:819)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$2.invoke(_Sequences.kt)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1.invokeSuspend(ObjectModelProvider.kt:240)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at org.utbot.fuzzer.ModelProvider$withFallback$1$1.invokeSuspend(ModelProvider.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
	at kotlin.sequences.SequencesKt__SequencesKt$shuffled$1.invokeSuspend(Sequences.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:110)
	at org.utbot.engine.UtBotSymbolicEngine$fuzzing$2.invokeSuspend(UtBotSymbolicEngine.kt:406)
	at org.utbot.engine.UtBotSymbolicEngine$fuzzing$2.invoke(UtBotSymbolicEngine.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:134)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$flowOf$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4$1$1.invokeSuspend(TestCaseGenerator.kt:369)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:158)
	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:51)
	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate(TestCaseGenerator.kt:157)
	at org.utbot.framework.plugin.api.TestCaseGenerator.generate$default(TestCaseGenerator.kt:144)
	at org.utbot.cli.GenerateTestsAbstractCommand.generateTestSets(GenerateTestsAbstractCommand.kt:162)
	at org.utbot.cli.GenerateTestsCommand.run(GenerateTestsCommand.kt:105)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at org.utbot.cli.ApplicationKt.main(Application.kt:31)
```

**Comment by SBOne-Kenobi** [comment]
> **Additional context**
> 
> Site backend was updated today. The error displayed now - on utbot.org - for the same code - is different from the one before: it has the stacktrace in statusDetails:
> 
> ```
> 09:28:01.659 | INFO  | AllInMemoryClassProvider | Loaded: 3 path entries, 19929 classes, 62321900 bytes
> 09:28:02.575 | INFO  | TestCaseGenerator | |> Resuming method Solution.q(Queue)
> 09:28:02.934 | ERROR | GenerateTestsCommand | An error has occurred while generating test for snippet Solution : java.lang.NullPointerException: member.declaringClass.`package` must not be null
> java.lang.NullPointerException: member.declaringClass.`package` must not be null
> 	at org.utbot.fuzzer.providers.ObjectModelProvider$Companion.isAccessible(ObjectModelProvider.kt:156)
> 	at org.utbot.fuzzer.providers.ObjectModelProvider$Companion.access$isAccessible(ObjectModelProvider.kt:145)
> 	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1$invokeSuspend$$inlined$with$lambda$1$1.invoke(ObjectModelProvider.kt:76)
> 	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1$invokeSuspend$$inlined$with$lambda$1$1.invoke(ObjectModelProvider.kt:37)
> 	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
> 	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
> 	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
> 	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
> 	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
> 	at kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:603)
> 	at kotlin.sequences.TakeSequence$iterator$1.<init>(Sequences.kt:411)
> 	at kotlin.sequences.TakeSequence.iterator(Sequences.kt:409)
> 	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$2.invoke(_Sequences.kt:819)
> 	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$2.invoke(_Sequences.kt)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
> 	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
> 	at org.utbot.fuzzer.providers.ObjectModelProvider$generate$1.invokeSuspend(ObjectModelProvider.kt:240)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
> 	at org.utbot.fuzzer.ModelProvider$withFallback$1$1.invokeSuspend(ModelProvider.kt:142)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
> 	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
> 	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
> 	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
> 	at kotlin.sequences.SequencesKt__SequencesKt$shuffled$1.invokeSuspend(Sequences.kt:140)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
> 	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
> 	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:110)
> 	at org.utbot.engine.UtBotSymbolicEngine$fuzzing$2.invokeSuspend(UtBotSymbolicEngine.kt:406)
> 	at org.utbot.engine.UtBotSymbolicEngine$fuzzing$2.invoke(UtBotSymbolicEngine.kt)
> 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
> 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
> 	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:134)
> 	at kotlinx.coroutines.flow.FlowKt__BuildersKt$flowOf$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
> 	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
> 	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4$1$1.invokeSuspend(TestCaseGenerator.kt:369)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
> 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
> 	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
> 	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:158)
> 	at org.utbot.framework.plugin.api.TestCaseGenerator$generate$4.invoke(TestCaseGenerator.kt:51)
> 	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
> 	at org.utbot.framework.plugin.api.TestCaseGenerator.generate(TestCaseGenerator.kt:157)
> 	at org.utbot.framework.plugin.api.TestCaseGenerator.generate$default(TestCaseGenerator.kt:144)
> 	at org.utbot.cli.GenerateTestsAbstractCommand.generateTestSets(GenerateTestsAbstractCommand.kt:162)
> 	at org.utbot.cli.GenerateTestsCommand.run(GenerateTestsCommand.kt:105)
> 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
> 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
> 	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
> 	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
> 	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
> 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
> 	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
> 	at org.utbot.cli.ApplicationKt.main(Application.kt:31)
> ```

@Markoutte

**Comment by SBOne-Kenobi** [comment]
@dtim 

**Additional context**
**JDK 8**. Plugin works on JDK 11, symbolic engine uses ConcurrentLinkedQueue as argument for the method, but in JDK 11 and JDK 8 implementations of this class are different, thus concrete executor fails, because symbolic engine tells rewrite non-existent static fields with non-existent types.
Test generation hangs without concrete executor (turned off).

**JDK 11**. Test generation hangs too without concrete executor.
