### ISSUE TITLE
IllegalStateException in Z3Translator

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#630]
**Description**

Generate test cases for the following code:

```java
public class Solution {
    public boolean func_1(List<Object> list, Object obj) {
        return list.contains(obj);
    }
}
```

**Actual behavior**

The following error occured:

```
Stacktrace: java.lang.IllegalStateException: translate of UtArrayApplyForAll expression at 

org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:417) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtArrayApplyForAll.accept(ExtendedArrayExpressions.kt:192) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:58) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtArraySelectExpression.accept(UtExpression.kt:217) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:82) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtAddrExpression.accept(UtExpression.kt:515) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:58) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtArraySelectExpression.accept(UtExpression.kt:217) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:82) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtAddrExpression.accept(UtExpression.kt:515) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:58) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtArraySelectExpression.accept(UtExpression.kt:217) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:133) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.UtBoolOpExpression.accept(UtExpression.kt:867) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:104) at org.utbot.engine.pc.Z3TranslatorVisitor.visit(Z3TranslatorVisitor.kt:35) at org.utbot.engine.pc.NotBoolExpression.accept(UtExpression.kt:700) at org.utbot.engine.pc.Z3TranslatorVisitor.translate(Z3TranslatorVisitor.kt:49) at org.utbot.engine.pc.UtSolver.translate(UtSolver.kt:320) at org.utbot.engine.pc.UtSolver.check(UtSolver.kt:224) at org.utbot.engine.selectors.BasePathSelector.checkUnsat(BasePathSelector.kt:64) at org.utbot.engine.selectors.BasePathSelector.checkUnsatIfFork(BasePathSelector.kt:70) at org.utbot.engine.selectors.BasePathSelector.poll(BasePathSelector.kt:83) at org.utbot.engine.UtBotSymbolicEngine$traverseImpl$1.invokeSuspend(UtBotSymbolicEngine.kt:509) at
```

**Additional context**

Bug was found by Dmitry Fedrushkov wx1076228

**Comment by CaelmBleidd** [comment]
I wanted to look into this bug but seems like it doesn't exist anymore in code from the description. @Damtev @dtim do you have similar examples?

**Comment by dtim** [comment]
I can reproduce this bug in `org.utbot.examples.java11.collections.ToArrayWithGeneratorTest#testGetGenericCollectionArgumentSize` unit test in [dtim/525_set_toarray_intfunction](https://github.com/UnitTestBot/UTBotJava/tree/dtim/525_set_toarray_intfunction) branch.

**Comment by dtim** [comment]
Code:
```
  public int getGenericCollectionArgumentSize(@NotNull Collection<T> arg) {
        return arg.size();
    }
```

**Comment by CaelmBleidd** [comment]
The reason (at least, one of them) is assumptions. 

`UtApplyForAll` should never occur during translation into a solver since it should be replaced in constraints during simplification/rewriting. This simplification happens in `org.utbot.engine.pc.BaseQuery#with` method, BUT we do not simplify given assumptions: 
```kotlin
fun add(hard: HardConstraint, soft: SoftConstraint, assumption: Assumption = Assumption()): UtSolver {
        // status can implicitly change here to UNDEFINED or UNSAT
        val newConstraints = constraints.with(hard.constraints, soft.constraints)
        val wantClone = (expectUndefined && newConstraints.status is UtSolverStatusUNDEFINED)
                || (!expectUndefined && newConstraints.status !is UtSolverStatusUNSAT)
``` 
Therefore, we have correctly transformed hard and soft constraints, but untouched assumptions. If we look a bit deeper into these assumptions, we will see something like that: 
```
(not (Gt (int (select (array org.utbot.engine.overrides.collections.RangeModifiableUnlimitedArray_end : Int32 -> Int32) addr: (select (array org.utbot.engine.overrides.collections.UtArrayList_elementData : Int32 -> Int32) addr: (select (select (store (array RefValues_Arrays : Int32 -> Int32 -> Int32) [addr: Int32 15]=(as const (Array Int32 -> Int32) Int32 0), [addr: (select (array org.utbot.engine.overrides.collections.RangeModifiableUnlimitedArray_storage : Int32 -> Int32) addr: (select (array org.utbot.engine.overrides.collections.UtHashSet_elementData : Int32 -> Int32) addr: (BVInt32 p0)))]=UtArrayApplyForAll(arrayExpression=(select (store (array RefValues_Arrays : Int32 -> Int32 -> Int32) [addr: Int32 15]=(as const (Array Int32 -> Int32) Int32 0)) addr: (select (array org.utbot.engine.overrides.collections.RangeModifiableUnlimitedArray_storage : Int32 -> Int32) addr: (select (array org.utbot.engine.overrides.collections.UtHashSet_elementData : Int32 -> Int32) addr: (BVInt32 p0)))), constraint=(org.utbot.engine.pc.UtExpression, org.utbot.engine.PrimitiveValue) -> org.utbot.engine.pc.UtBoolExpression)) addr: (select (array org.utbot.engine.overrides.collections.RangeModifiableUnlimitedArray_storage : Int32 -> Int32) addr: (select (array org.utbot.engine.overrides.collections.UtHashSet_elementData : Int32 -> Int32) addr: (BVInt32 p0)))) Int32 1)))) (int Int32 10)))
```
It might be a bit hard, but we can find `=UtArrayApplyForAll(arrayExpression` construction in it. 

We must simplify assumptions to avoid such cases, seems like everything should be alright after this fix. I spoke with @Damtev , he's fixing it
