### ISSUE TITLE
AssertionError from SootResolver

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#667]
**Description**

AssertionError is thrown at soot.SootResolver.resolveClass

**To Reproduce**

1. A commercial Maven project was opened in IntelliJ Idea
2. Use plugin to generate tests (the build#231, one of the latest from main branch)
3. A package with several classes was selected and test generation was initiated

**Expected behavior**

No exception was awaited.

**Actual behavior**

java.lang.AssertionError
	at soot.SootResolver.resolveClass was thrown

**Visual proofs (screenshots, logs, images)**

~~~
java.lang.AssertionError
	at soot.SootResolver.resolveClass(SootResolver.java:146)
	at soot.Scene.loadClass(Scene.java:992)
	at soot.Scene.loadClassAndSupport(Scene.java:977)
	at soot.Scene.loadNecessaryClasses(Scene.java:1785)
	at org.utbot.framework.util.SootUtilsKt.runSoot(SootUtils.kt:86)
	at org.utbot.framework.plugin.api.TestCaseGenerator.<init>(TestCaseGenerator.kt:81)
	at org.utbot.framework.plugin.api.TestCaseGenerator.<init>(TestCaseGenerator.kt:61)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.4
Maven project with JDK 1.8

**Additional context**

Not sure which class was being processed.

**Comment by alisevych** [comment]
Not reproducing
