### ISSUE TITLE
Generate tests action throws NoClassDefFoundError: com/android/tools/idea/gradle/project/GradleProjectInfo

### ISSUE THREAD

**Issue by sergeypospelov** [UnitTestBot/UTBotJava#715]
**Description**

When you run one of the latest plugins, an internal plugin error occurs. Most probably it's caused by the latest changes in `ModuleUtils.kt`.

**To Reproduce**

1. Install plugin from https://github.com/UnitTestBot/UTBotJava/actions/runs/2832509326
2. Open any project
3. Run `Create Tests with UtBot` action

**Expected behavior**

Dialog opens.

**Actual behavior**

Internal IDE error occurred

Stacktrace:
```
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/project/GradleProjectInfo
	at org.utbot.intellij.plugin.ui.utils.ModuleUtilsKt.isGradle(ModuleUtils.kt:150)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialog(UtTestsDialogProcessor.kt:85)
	at org.utbot.intellij.plugin.generator.UtTestsDialogProcessor.createDialogAndGenerateTests(UtTestsDialogProcessor.kt:70)
	at org.utbot.intellij.plugin.ui.actions.GenerateTestsAction.actionPerformed(GenerateTestsAction.kt:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235)
	at com.intellij.ide.actions.GotoActionAction.performActionImpl(GotoActionAction.java:113)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:80)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
```

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/30112817/184313070-fa7e8f31-6cc8-42df-a4bd-c0bd4626a5b9.png)

**Environment**

- Windows 10
- IntelliJ IDEA 2022.1.3 (Ultimate Edition)
- IDEA runtime version: 11.0.15
- VM: OpenJDK 64-Bit Server VM by JetBrains

**Comment by alisevych** [comment]
Not reproduced with the same versions of OS, IDEA and UTBot - may be some other settings influent this.

**Comment by Markoutte** [comment]
To reproduce:

1. Disable Android plugin
2. Try to open dialog

The problem that `GradleProjectInfo` is a class from Android plugin. By default this plugin is enabled, but it can be disabled by a user.

**Comment by EgorkaKulikov** [comment]
Seems to b fixed in https://github.com/UnitTestBot/UTBotJava/pull/935
