### ISSUE TITLE
JavaScript: IllegalStateException: Number too big

### ISSUE THREAD

**Issue by tamarinvs19** [UnitTestBot/UTBotJava#723]
**Description**

Java exception `java.lang.IllegalStateException: Number too big` during test generation for simple function. 

**To Reproduce**

1. Run the JavaScript project in IntelliJ Idea with file `/scenarios/hello.js`
2. Write this code to file `/scenarios/hello.js`:

```js
class MyTestClass {
    f(x, y) {
        y = y * 1000000000
        return x / y
    }
}
```

3. Use plugin on function `f` to generate tests

**Expected behavior**

Tests are supposed to be generated.
No IDE errors should be thrown.

**Actual behavior**

Plugin Failed. There is exception in IDE Fatal Error window

**Visual proofs (screenshots, logs, images)**

__Stack Trace__

~~~
java.lang.IllegalStateException: Number too big
	at utils.GraalValueKt.toAny(GraalValue.kt:23)
	at org.utbot.intellij.plugin.generator.JsDialogProcessor$createTests$1$run$1$2.invokeSuspend(JsDialogProcessor.kt:186)
	at org.utbot.intellij.plugin.generator.JsDialogProcessor$createTests$1$run$1$2.invoke(JsDialogProcessor.kt)
	at org.utbot.common.ConcurrencyKt$runBlockingWithCancellationPredicate$1$job$1.invokeSuspend(Concurrency.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.utbot.common.ConcurrencyKt.runBlockingWithCancellationPredicate(Concurrency.kt:38)
	at org.utbot.intellij.plugin.generator.JsDialogProcessor$createTests$1$run$1.invoke(JsDialogProcessor.kt:107)
	at org.utbot.intellij.plugin.generator.JsDialogProcessor$createTests$1$run$1.invoke(JsDialogProcessor.kt:103)
	at org.utbot.common.ConcurrencyKt.runIgnoringCancellationException(Concurrency.kt:47)
	at org.utbot.intellij.plugin.generator.JsDialogProcessor$createTests$1.run(JsDialogProcessor.kt:106)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

**Environment**

_TestFramework_: Mocha
_OS_: Windows 10
_Intellij IDEA_: IntelliJ IDEA 2020.2 (Ultimate Edition), Build #IU-202.6397.94, built on July 27, 2020
_Runtime version_: 11.0.7+10-b944.20 amd64

**Comment by rudolf101** [comment]
@tamarinvs19 
Fixed with [commit](https://github.com/UnitTestBot/UTBotJava/commit/7fa0e6198df4ed4e358c32754c8ec8b78fd1c3b3)

**Comment by rudolf101** [comment]
@tamarinvs19 
Fixed with [commit](https://github.com/UnitTestBot/UTBotJava/commit/7fa0e6198df4ed4e358c32754c8ec8b78fd1c3b3)
