### ISSUE TITLE
Doesn't work string template

### ISSUE THREAD

**Issue by alexeyfridman** [UnitTestBot/UTBotJava#75]
Following code doesn't work

```java
OGGER.info("query snippet data cost: {}s", (float) (end.getTime() - begin.getTime()) / 1000);
```

**Comment by alisevych** [comment]
Verified on latest main: reproducing.
Concrete Execution errors are present though stack traces are different:

```java
11:49:11.880 | DEBUG | InstrumentedProcess       | invokeMethod failure 
11:49:11.880 | ERROR | InstrumentedProcess       |  | java.lang.IllegalArgumentException: Can not set java.util.concurrent.ConcurrentHashMap field java.util.Properties.map to java.util.HashMap
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
	at java.base/java.lang.reflect.Field.set(Field.java:780)
	at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:200)
	at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:131)
	at org.utbot.framework.concrete.MockValueConstructor.mockAndGet(MockValueConstructor.kt:475)
	at org.utbot.framework.concrete.MockValueConstructor.computeConcreteValuesForMethods(MockValueConstructor.kt:240)
	at org.utbot.framework.concrete.MockValueConstructor.mockMethods(MockValueConstructor.kt:257)
	at org.utbot.framework.concrete.MockValueConstructor.mockStaticMethods(MockValueConstructor.kt:279)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:175)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.withStaticFields(UtExecutionInstrumentation.kt:320)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:116)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:128)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:124)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1$1.invoke(ClientProcessUtil.kt:94)
	at org.utbot.rd.IdleWatchdog.wrapActive(ClientProcessUtil.kt:81)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1.invoke(ClientProcessUtil.kt:93)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:362)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda-3(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

11:49:11.923 | DEBUG | InstrumentedProcess       | received invokeMethod request: A, messageFormatValue(I)Ljava/lang/String; 
WARNING: Illegal reflective access by org.utbot.framework.concrete.MockValueConstructor (file:/C:/Users/lWX1182794/AppData/Roaming/JetBrains/IntelliJIdea2022.2/plugins/utbot-intellij/lib/utbot-framework-2022.11.569..jar) to field java.security.Provider.initialized
11:49:11.928 | DEBUG | InstrumentedProcess       | invokeMethod failure 
11:49:11.928 | ERROR | InstrumentedProcess       |  | java.lang.IllegalArgumentException: Can not set java.util.concurrent.ConcurrentHashMap field java.util.Properties.map to java.util.HashMap
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
	at java.base/java.lang.reflect.Field.set(Field.java:780)
	at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:200)
	at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:131)
	at org.utbot.framework.concrete.MockValueConstructor.mockAndGet(MockValueConstructor.kt:475)
	at org.utbot.framework.concrete.MockValueConstructor.computeConcreteValuesForMethods(MockValueConstructor.kt:240)
	at org.utbot.framework.concrete.MockValueConstructor.mockMethods(MockValueConstructor.kt:257)
	at org.utbot.framework.concrete.MockValueConstructor.mockStaticMethods(MockValueConstructor.kt:279)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:175)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.withStaticFields(UtExecutionInstrumentation.kt:320)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:116)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:128)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:124)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1$1.invoke(ClientProcessUtil.kt:94)
	at org.utbot.rd.IdleWatchdog.wrapActive(ClientProcessUtil.kt:81)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1.invoke(ClientProcessUtil.kt:93)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:362)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda-3(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

11:49:11.932 | DEBUG | InstrumentedProcess       | received invokeMethod request: A, messageFormatValue(I)Ljava/lang/String; 
11:49:11.935 | DEBUG | InstrumentedProcess       | invokeMethod failure 
11:49:11.935 | ERROR | InstrumentedProcess       |  | java.lang.IllegalStateException: No field $__is_mock_null in class sun.security.action.GetPropertyAction
	at org.utbot.framework.concrete.MethodMockController.<init>(MethodMockController.kt:38)
	at org.utbot.framework.concrete.MockValueConstructor.mockMethods(MockValueConstructor.kt:261)
	at org.utbot.framework.concrete.MockValueConstructor.mockStaticMethods(MockValueConstructor.kt:279)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:175)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.withStaticFields(UtExecutionInstrumentation.kt:320)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:116)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:128)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:124)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1$1.invoke(ClientProcessUtil.kt:94)
	at org.utbot.rd.IdleWatchdog.wrapActive(ClientProcessUtil.kt:81)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1.invoke(ClientProcessUtil.kt:93)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:362)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda-3(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

11:49:11.939 | DEBUG | InstrumentedProcess       | received invokeMethod request: A, messageFormatValue(I)Ljava/lang/String; 
11:49:11.941 | DEBUG | InstrumentedProcess       | invokeMethod success 
11:49:11.950 | DEBUG | InstrumentedProcess       | received invokeMethod request: A, messageFormatValue(I)Ljava/lang/String; 
11:49:11.952 | DEBUG | InstrumentedProcess       | invokeMethod failure 
11:49:11.952 | ERROR | InstrumentedProcess       |  | java.lang.IllegalArgumentException: Can not set java.util.concurrent.ConcurrentHashMap field java.util.Properties.map to java.util.HashMap
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
	at java.base/java.lang.reflect.Field.set(Field.java:780)
	at org.utbot.framework.concrete.MockValueConstructor.constructObject(MockValueConstructor.kt:200)
	at org.utbot.framework.concrete.MockValueConstructor.construct(MockValueConstructor.kt:131)
	at org.utbot.framework.concrete.MockValueConstructor.mockAndGet(MockValueConstructor.kt:475)
	at org.utbot.framework.concrete.MockValueConstructor.computeConcreteValuesForMethods(MockValueConstructor.kt:240)
	at org.utbot.framework.concrete.MockValueConstructor.mockMethods(MockValueConstructor.kt:257)
	at org.utbot.framework.concrete.MockValueConstructor.mockStaticMethods(MockValueConstructor.kt:279)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:175)
	at org.utbot.framework.concrete.UtExecutionInstrumentation$invoke$1$concreteExecutionResult$1.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.withStaticFields(UtExecutionInstrumentation.kt:320)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:173)
	at org.utbot.framework.concrete.UtExecutionInstrumentation.invoke(UtExecutionInstrumentation.kt:116)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:128)
	at org.utbot.instrumentation.process.InstrumentedProcessMainKt$setup$2.invoke(InstrumentedProcessMain.kt:124)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1$1.invoke(ClientProcessUtil.kt:94)
	at org.utbot.rd.IdleWatchdog.wrapActive(ClientProcessUtil.kt:81)
	at org.utbot.rd.IdleWatchdog$wrapActiveCall$1.invoke(ClientProcessUtil.kt:93)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.IRdEndpoint$set$1.invoke(TaskInterfaces.kt:182)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:362)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase.queue$lambda-3(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

11:49:11.975 | DEBUG | InstrumentedProcess       | stop request 
11:49:11.976 | INFO  | InstrumentedProcess       | runBlocking ending 
11:49:11.976 | INFO  | InstrumentedProcess       | runBlocking ended 
```
